import "./globals.css";
import Footer from "@/components/Footer";
import { Headeer } from "@/components/Header";

export const metadata = {
  title: "Ki Chai",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Headeer></Headeer>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
