import { Headeer } from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const res = await fetch("https://api.github.com/repos/vercel/next.js", {
  //   cache: "no-store",
  //   next: {
  //     revalidate: 5,
  //   },
  // });
  // const data = await res.json();
  // console.log(data);
  return (
    <html lang="en">
      <body>
        <Headeer></Headeer>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
